[Rainmeter]
Update=100
DefaultUpdateDivider=20
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Shows Stats of Upto 4 Drives : Used\Total---Free | Automatically detects available drive letters|Drive letters can be assigned manually in Variables
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

@include3=DriveLetters#Letters#.inc

;-------Disk--Info

[MeasureDiskSize1]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter1]
Total=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskUsed1]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter1]
MaxValue=[MeasureDiskSize1]
InvertMeasure=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskFree1]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter1]
MaxValue=[MeasureDiskSize1]
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskSize2]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter2]
Total=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskUsed2]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter2]
MaxValue=[MeasureDiskSize2]
InvertMeasure=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskFree2]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter2]
MaxValue=[MeasureDiskSize2]
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskSize3]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter3]
Total=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskUsed3]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter3]
MaxValue=[MeasureDiskSize3]
InvertMeasure=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskFree3]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter3]
MaxValue=[MeasureDiskSize3]
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskSize4]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter4]
Total=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskUsed4]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter4]
MaxValue=[MeasureDiskSize4]
InvertMeasure=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats 

[MeasureDiskFree4]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter4]
MaxValue=[MeasureDiskSize4]
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats 

[MeasureDiskSize5]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter5]
Total=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskUsed5]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter5]
MaxValue=[MeasureDiskSize5]
InvertMeasure=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats 

[MeasureDiskFree5]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter5]
MaxValue=[MeasureDiskSize5]
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats 

[MeasureDiskSize6]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter6]
Total=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats

[MeasureDiskUsed6]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter6]
MaxValue=[MeasureDiskSize6]
InvertMeasure=1
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats 

[MeasureDiskFree6]
Measure=FreeDiskSpace
Drive=[MeasureDriveLetter6]
MaxValue=[MeasureDiskSize6]
IgnoreRemovable=0
DynamicVariables=1
Group=DriveStats 

;----------
[DriveHeight]
Measure=Calc
Formula=22+#Height1#+#Height2#+#Height3#+#Height4#+#Height5#+#Height6#
OnChangeAction=[!UpdateMeter *][!Redraw]
DynamicVariables=1

[DriveHead]
Meter=Shape
Shape=Line 0,0,275,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[DriveBg]
Meter=Shape
Shape=Rectangle 0,5,275,[DriveHeight] | Extend DriveBgFill | StrokeWidth 0
DriveBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption DriveBg DriveBgFill "Fill Color #HoverGround#"][!UpdateMeter DriveBg][!Redraw]
MouseLeaveAction=[!SetOption DriveBg DriveBgFill "Fill Color #BackGround#"][!UpdateMeter DriveBg][!Redraw]
DynamicVariables=1
X=r
Y=r

[Drive1Letter]
Meter=String
MeasureName=MeasureDriveLetter1
MeterStyle=TextStyle1
FontSize=15
Group=D1
X=5r
Y=20r

[Drive1Bar]
Meter=Bar
MeasureName=MeasureDiskUsed1
BarOrientation=Horizontal
BarColor=#Color2#
SolidColor=80,80,80,100
Group=D1
X=20r
y=2r
W=240
H=18

[Drive1Used]
Meter=String
MeasureName=MeasureDiskUsed1
MeasureName2=MeasureDiskSize1
Text=%1 / %2
MeterStyle=BarText
FontSize=12
Group=D1
AutoScale=1
X=10r
Y=r

[Drive1Free]
Meter=String
MeasureName=MeasureDiskFree1
MeterStyle=BarText
FontSize=12
AutoScale=1
StringAlign=Right
Group=D1
H=30
X=220r
Y=r

[Drive2Letter]
Meter=String
MeasureName=MeasureDriveLetter2
MeterStyle=TextStyle1
FontSize=15
Group=D2
X=-250r
Y=R

[Drive2Bar]
Meter=Bar
MeasureName=MeasureDiskUsed2
BarOrientation=Horizontal
BarColor=#Color2#
SolidColor=80,80,80,100
Group=D2
X=20r
y=2r
W=240
H=18

[Drive2Used]
Meter=String
MeasureName=MeasureDiskUsed2
MeasureName2=MeasureDiskSize2
Text=%1 / %2
MeterStyle=BarText
FontSize=12
Group=D2
AutoScale=1
X=10r
Y=r

[Drive2Free]
Meter=String
MeasureName=MeasureDiskFree2
MeterStyle=BarText
FontSize=12
AutoScale=1
StringAlign=Right
Group=D2
H=30
X=220r
Y=r

[Drive3Letter]
Meter=String
MeasureName=MeasureDriveLetter3
MeterStyle=TextStyle1
FontSize=15
Group=D3
X=-250r
Y=R

[Drive3Bar]
Meter=Bar
MeasureName=MeasureDiskUsed3
BarOrientation=Horizontal
BarColor=#Color2#
SolidColor=80,80,80,100
Group=D3
X=20r
y=2r
W=240
H=18

[Drive3Used]
Meter=String
MeasureName=MeasureDiskUsed3
MeasureName2=MeasureDiskSize3
Text=%1 / %2
MeterStyle=BarText
FontSize=12
AutoScale=1
Group=D3
X=10r
Y=r

[Drive3Free]
Meter=String
MeasureName=MeasureDiskFree3
MeterStyle=BarText
FontSize=12
AutoScale=1
StringAlign=Right
Group=D3
H=30
X=220r
Y=r

[Drive4Letter]
Meter=String
MeasureName=MeasureDriveLetter4
MeterStyle=TextStyle1
FontSize=15
Group=D4
X=-250r
Y=R

[Drive4Bar]
Meter=Bar
MeasureName=MeasureDiskUsed4
BarOrientation=Horizontal
BarColor=#Color2#
SolidColor=80,80,80,100
Group=D4
X=20r
y=2r
W=240
H=18

[Drive4Used]
Meter=String
MeasureName=MeasureDiskUsed4
MeasureName2=MeasureDiskSize4
Text=%1 / %2
MeterStyle=BarText
FontSize=12
AutoScale=1
Group=D4
X=10r
Y=r

[Drive4Free]
Meter=String
MeasureName=MeasureDiskFree4
MeterStyle=BarText
FontSize=12
AutoScale=1
StringAlign=Right
Group=D4
H=30
X=220r
Y=r

[Drive5Letter]
Meter=String
MeasureName=MeasureDriveLetter5
MeterStyle=TextStyle1
FontSize=15
Group=D5
X=-250r
Y=R

[Drive5Bar]
Meter=Bar
MeasureName=MeasureDiskUsed5
BarOrientation=Horizontal
BarColor=#Color2#
SolidColor=80,80,80,100
Group=D5
X=20r
y=2r
W=240
H=18

[Drive5Used]
Meter=String
MeasureName=MeasureDiskUsed5
MeasureName2=MeasureDiskSize5
Text=%1 / %2
MeterStyle=BarText
FontSize=12
AutoScale=1
Group=D5
X=10r
Y=r

[Drive5Free]
Meter=String
MeasureName=MeasureDiskFree5
MeterStyle=BarText
FontSize=12
AutoScale=1
StringAlign=Right
Group=D5
H=30
X=220r
Y=r

[Drive6Letter]
Meter=String
MeasureName=MeasureDriveLetter6
MeterStyle=TextStyle1
FontSize=15
Group=D6
X=-250r
Y=R

[Drive6Bar]
Meter=Bar
MeasureName=MeasureDiskUsed6
BarOrientation=Horizontal
BarColor=#Color2#
SolidColor=80,80,80,100
Group=D6
X=20r
y=2r
W=240
H=18

[Drive6Used]
Meter=String
MeasureName=MeasureDiskUsed6
MeasureName2=MeasureDiskSize6
Text=%1 / %2
MeterStyle=BarText
FontSize=12
AutoScale=1
Group=D6
X=10r
Y=r

[Drive6Free]
Meter=String
MeasureName=MeasureDiskFree6
MeterStyle=BarText
FontSize=12
AutoScale=1
StringAlign=Right
Group=D6
H=30
X=220r
Y=r