[Rainmeter]
Update=100
DefaultUpdateDivider=-1
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Edit Launcher name and Path in Variables | Double click Highlighted BackGround or Single Click Icon on Right to Execute
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[LauncherHead]
Meter=Shape
Shape=Line 0,0,260,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[LauncherBg]
Meter=Shape
Shape=Rectangle 0,4,260,190 | Extend LauncherBgFill | StrokeWidth 0
LauncherBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption LauncherBg LauncherBgFill "Fill Color #HoverGround#"][!UpdateMeter LauncherBg][!Redraw]
MouseLeaveAction=[!SetOption LauncherBg LauncherBgFill "Fill Color #BackGround#"][!UpdateMeter LauncherBg][!Redraw]
X=r
Y=r

[Launch1Bg]
Meter=Shape
Shape=Rectangle 0,0,260,30 | Extend Launch1Fill | StrokeWidth 0
Launch1Fill=Fill Color #BackGround#
MouseOverAction=[!SetOption Launch1Bg Launch1Fill "Fill Color #HoverGround#"][!UpdateMeter Launch1Bg][!Redraw]
MouseLeaveAction=[!SetOption Launch1Bg Launch1Fill "Fill Color #BackGround#"][!UpdateMeter Launch1Bg][!Redraw]
LeftMouseDoubleClickAction=["#LaunchPath1#"]
X=r
Y=10r

[Launch1Ico]
Meter=Button
ButtonImage=#@#Images\LaunchIco.png
ButtonCommand=["#LaunchPath1#"]
SolidColor=0,0,0,1
X=220r
Y=5r

[Launch1Name]
Meter=String
MeterStyle=TextStyle1
Text=#LaunchName1#
StringAlign=Right
X=-10r
y=r
;-------Launch 2----
[Launch2Bg]
Meter=Shape
Shape=Rectangle 0,0,260,30 | Extend Launch2Fill | StrokeWidth 0
Launch2Fill=Fill Color #BackGround#
MouseOverAction=[!SetOption Launch2Bg Launch2Fill "Fill Color #HoverGround#"][!UpdateMeter Launch2Bg][!Redraw]
MouseLeaveAction=[!SetOption Launch2Bg Launch2Fill "Fill Color #BackGround#"][!UpdateMeter Launch2Bg][!Redraw]
LeftMouseDoubleClickAction=["#LaunchPath2#"]
X=-210r
Y=25r

[Launch2Ico]
Meter=Button
ButtonImage=#@#Images\LaunchIco.png
ButtonCommand=["#LaunchPath2#"]
SolidColor=0,0,0,1
X=220r
Y=5r

[Launch2Name]
Meter=String
MeterStyle=TextStyle1
Text=#LaunchName2#
StringAlign=Right
X=-10r
y=r
;-----------Launch-3--------
[Launch3Bg]
Meter=Shape
Shape=Rectangle 0,0,260,30 | Extend Launch3Fill | StrokeWidth 0
Launch3Fill=Fill Color #BackGround#
MouseOverAction=[!SetOption Launch3Bg Launch3Fill "Fill Color #HoverGround#"][!UpdateMeter Launch3Bg][!Redraw]
MouseLeaveAction=[!SetOption Launch3Bg Launch3Fill "Fill Color #BackGround#"][!UpdateMeter Launch3Bg][!Redraw]
LeftMouseDoubleClickAction=["#LaunchPath3#"]
X=-210r
Y=25r

[Launch3Ico]
Meter=Button
ButtonImage=#@#Images\LaunchIco.png
ButtonCommand=["#LaunchPath3#"]
SolidColor=0,0,0,1
X=220r
Y=5r

[Launch3Name]
Meter=String
MeterStyle=TextStyle1
Text=#LaunchName3#
StringAlign=Right
X=-10r
y=r
;-------Launch-4-------------
[Launch4Bg]
Meter=Shape
Shape=Rectangle 0,0,260,30 | Extend Launch4Fill | StrokeWidth 0
Launch4Fill=Fill Color #BackGround#
MouseOverAction=[!SetOption Launch4Bg Launch4Fill "Fill Color #HoverGround#"][!UpdateMeter Launch4Bg][!Redraw]
MouseLeaveAction=[!SetOption Launch4Bg Launch4Fill "Fill Color #BackGround#"][!UpdateMeter Launch4Bg][!Redraw]
LeftMouseDoubleClickAction=["#LaunchPath4#"]
X=-210r
Y=25r

[Launch4Ico]
Meter=Button
ButtonImage=#@#Images\LaunchIco.png
ButtonCommand=["#LaunchPath4#"]
SolidColor=0,0,0,1
X=220r
Y=5r

[Launch4Name]
Meter=String
MeterStyle=TextStyle1
Text=#LaunchName4#
StringAlign=Right
X=-10r
y=r
;-------Launch-5----------
[Launch5Bg]
Meter=Shape
Shape=Rectangle 0,0,260,30 | Extend Launch5Fill | StrokeWidth 0
Launch5Fill=Fill Color #BackGround#
MouseOverAction=[!SetOption Launch5Bg Launch5Fill "Fill Color #HoverGround#"][!UpdateMeter Launch5Bg][!Redraw]
MouseLeaveAction=[!SetOption Launch5Bg Launch5Fill "Fill Color #BackGround#"][!UpdateMeter Launch5Bg][!Redraw]
LeftMouseDoubleClickAction=["#LaunchPath5#"]
X=-210r
Y=25r

[Launch5Ico]
Meter=Button
ButtonImage=#@#Images\LaunchIco.png
ButtonCommand=["#LaunchPath5#"]
SolidColor=0,0,0,1
X=220r
Y=5r

[Launch5Name]
Meter=String
MeterStyle=TextStyle1
Text=#LaunchName5#
StringAlign=Right
X=-10r
y=r
;--------Launch-6------------
[Launch6Bg]
Meter=Shape
Shape=Rectangle 0,0,260,30 | Extend Launch6Fill | StrokeWidth 0
Launch6Fill=Fill Color #BackGround#
MouseOverAction=[!SetOption Launch6Bg Launch6Fill "Fill Color #HoverGround#"][!UpdateMeter Launch6Bg][!Redraw]
MouseLeaveAction=[!SetOption Launch6Bg Launch6Fill "Fill Color #BackGround#"][!UpdateMeter Launch6Bg][!Redraw]
LeftMouseDoubleClickAction=["#LaunchPath6#"]
X=-210r
Y=25r

[Launch6Ico]
Meter=Button
ButtonImage=#@#Images\LaunchIco.png
ButtonCommand=["#LaunchPath6#"]
SolidColor=0,0,0,1
X=220r
Y=5r

[Launch6Name]
Meter=String
MeterStyle=TextStyle1
Text=#LaunchName6#
StringAlign=Right
X=-10r
y=r