[Variables]
Port1=G:
Port2=H:
Port3=I:

;----------
Latitude=30.9
Longitude=75.85
Region=Punjab
Country=India
;----------
Font1=Cyberverse Condensed
Font2=Autobus

Battery=Battery

;--------
None=
BotWallSet=#BotWallpaper#
BotWallPaper=[!SetWallpaper "#@#images\abot.jpg" Stretch]
ConWallSet=#ConWallPaper#
ConWallPaper=[!SetWallpaper "#@#images\dcon.jpg" Stretch]
;--Do not touch BotWallpaper and ConWallPaper, as this cause disturbances in settings skin.While feel free to place your own image under name 'abot|dcon.jpg'
;---Colors

BotColor1=255,255,255
BotColor2=21,44,214
BotColor3=230,0,0
BotPlayerColor=220,160,0

ConColor1=255,255,255
ConColor2=170,0,170
ConColor3=200,0,0
ConPlayerColor=220,160,0
;=======Launchers===
LaunchName1=Launcher 1
LaunchPath1=Path 1

LaunchName2=Launcher 2
LaunchPath2=Path 2

LaunchName3=Launcher 3
LaunchPath3=Path 3

LaunchName4=Launcher 4
LaunchPath4=Path 4

LaunchName5=Launcher 5
LaunchPath5=Path 5

LaunchName6=Launcher 6
LaunchPath6=Path 6

;----------------------
Name=Rajnoor Brar

;----------Drives======
Drive1Name=Disk D: All Games
Drive2Name=Disk E: Mulimedia Files
Drive3Name=Disk F: Softwares, Files, Pics

Drive1=D:
Drive2=E:
Drive3=F:

;Music=============================
PlayerPath=C:\Program Files (x86)\MusicBee\MusicBee.exe

PlDe=CAD
PlSe=AIMP

;Change PlDe to your First Choice player(One you use most),PlSe to second choice player
;List of valid values are :

;- AIMP: PlayerName=AIMP
;  Fully supported. Tested with AIMP 2.61.

;- foobar2000: PlayerName=CAD
;  Fully supported. The foo_cad plugin (download) needs to be installed,
;  find it at http://poiru.github.com/foo-cad/

;- iTunes: PlayerName=iTunes
;  Fully supported. Tested with iTunes 10.2.

;- J. River Media Center and Media Jukebox: PlayerName=CAD
;  Fully supported through the CAD interface. The intcad plugin needs to be installed,
;  find it at http://code.google.com/p/jr-intcad/

;- MediaMonkey: PlayerName=MediaMonkey
;  Fully supported. Tested with MediaMonkey 3.2.5.
 
;- MusicBee: PlayerName=CAD
;  Fully supported. MusicBee 1.2 (or higher) is required.
  
;- Winamp: PlayerName=Winamp
;  Fully supported.

;- VLC: PlayerName=CAD
;  Fully supported. The libcad plugin for VLC must be installed,
;  find it at http://code.google.com/p/vlc-libcad/
 
;- WMP: PlayerName=WMP
;  Fully supported, except for the Repeat / Shuffle types.

;==== If the Player codes, especially CAD, aren't working, Check to open their setting, and activate the Cover Art Display plugin, or any realted such setting.

