[Rainmeter]
Update=100
DefaultUpdateDivider=10
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Day, Date Month | Hour : Minute | Seconds
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[MeasureDate]
Measure=Time
Format=%d

[MeasureDay]
Measure=Time
Format=%A

[MeasureMonth]
Measure=Time
Format=%B

[MeasureHour]
Measure=Time
Format="%H"

[MeasureMin]
Measure=Time
Format="%M"

[MeasureSec]
Measure=Time
Format=%S
UpdateDivider=5
MaxValue=60
MinValue=0

[TimeHead]
Meter=Shape
Shape=Line 0,0,280,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[TimeBg]
Meter=Shape
Shape=Rectangle 0,4,280,145 | Extend TimeBgFill | StrokeWidth 0
TimeBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption TimeBg TimeBgFill "Fill Color #HoverGround#"][!UpdateMeter TimeBg][!Redraw]
MouseLeaveAction=[!SetOption TimeBg TimeBgFill "Fill Color #BackGround#"][!UpdateMeter TimeBg][!Redraw]
X=r
Y=r

[MeterDate]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureDay
MeasureName2=MeasureDate
MeasureName3=MeasureMonth
Text=%1, %2 %3
FontSize=22
StringAlign=Right
X=270r
Y=5r

[MeterTime]
Meter=String
MeterStyle=TextStyle2
MeasureName=MeasureHour
MeasureName2=MeasureMin
Text=%1:%2
FontSize=55
StringAlign=Right
X=-15r
Y=20r

[MeterSec]
Meter=Bar
MeasureName=MeasureSec
W=200
H=16
X=-185r
Y=100r
SolidColor=80,80,80,100
BarColor=#color2#,235
BarOrientation=Horizontal
UpdateDivider=5
Flip=1
