[Rainmeter]
AntiAlias=1
Author=Rajnoor Brar
OnRefreshAction=[!ZPos "2"]
;==================Player-Choose-============================;
;When both players are in running state ,choose which to play,other will be paused

[Variables]
@include= #@#\Config.inc
Color2=0,78,255
Color3=230,0,0
Color1=255,255,255

[MusicStyle1]
FontColor=#Color1#,255
FontEffectColor=#Color3#,200
StringEffect=BORDER
StringStyle=NORMAL
FontFace=Transformers
AntiAlias=1
StringCase=lower

[MusicStyle2]
FontColor=#Color3#,255
StringEffect=NONE
StringStyle=NORMAL
FontFace=Transformers
AntiAlias=1
StringCase=lower


[PlSe]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#PlSe#
PlayerType=STATE
IfCondition=([DefaultPlayerName:W] < 176)
IfTrueAction=[!SetOption PlayerBoth X "([DefaultPlayerName:X]+225)"][!SetOption MusicBox3 X "([DefaultPlayerName:X]+220)"]
IfFalseAcion=[!SetOption PlayerBoth X "([DefaultPlayerName:X]+[DefaultPlayerName:W]+78)"][!SetOption MusicBox3 X "([MusicBox1:X]+[DefaultPlayerName:W]+70)"]

[PlDe]
Measure=Plugin
Plugin=NowPlaying.dll
PlayerName=#PlDe#
PlayerType=STATE

[PLDBackBlur]
Meter=Image
SolidColor=0,0,0,190
H=#workareaheight#
W=#workareawidth#

[PLDBackground]
Meter=Image
ImageName=#@#\Images\music.jpg
X=((#workareawidth#/2)-(650/2))
Y=((#workareaheight#/2)-(400/2))
W=650
H=400

[PLDFrontground]
Meter=Image
ImageName=#@#\Images\powbg.png
X=((#workareawidth#/2)-(603/2))
Y=((#workareaheight#/2)-(393/2))
ImageTint=#Color2#,100

[TFTitle]
Meter=String
MeterStyle=MusicStyle1
FontEffectColor=#Color2#,200
FontSize=35
StringAlign=Right
X=400r
Y=100r
Text="TRANSFORMERS"

[MusicText1]
Meter=String
MeterStyle=MusicStyle1
FontSize=11
StringAlign=Right
X=-120r
Y=55r
Text=SELECT PLAYER YOU WANT TO PLAY 

[MusicScreenText]
Meter=String
MeterStyle=MusicStyle1
FontEffectColor=#Color2#,200
FontSize=31
StringAlign=left
X=-255r
Y=10r
Text="_SELECT TO PLAY"

[MusicBox1]
Meter=IMAGE
SolidColor=#Color3#,160
W=([DefaultPlayerName:W]+20)
H=30
X=30r
Y=10R
MouseOverAction=[!SetOption DefaultPlayerName MeterStyle MusicStyle2][!SetOption MusicBox1 SolidColor #Color1#,250][PLAY #@#01.WAV]
MouseLeaveAction=[!SetOption DefaultPlayerName MeterStyle MusicStyle1][!SetOption MusicBox1 SolidColor #Color3#,160]
LeftMouseUpAction=[!CommandMeasure PlDe "Play"][!DeactivateConfig]
DynamicVariables=1

[MusicBox2]
Meter=IMAGE
SolidColor=#Color3#,160
W=([SecondaryPlayerName:W]+20)
H=30
X=20r
Y=45r
MouseOverAction=[!SetOption SecondaryPlayerName MeterStyle MusicStyle2][!SetOption MusicBox2 SolidColor #Color1#,250][PLAY #@#01.WAV]
MouseLeaveAction=[!SetOption SecondaryPlayerName  MeterStyle MusicStyle1][!SetOption MusicBox2 SolidColor #Color3#,160]
LeftMouseUpAction=[!CommandMeasure PlSe "Play"][!DeactivateConfig]
DynamicVariables=1

[MusicBox3]
Meter=IMAGE
SolidColor=#Color3#,160
W=65
H=30
X=([MusicBox1:X]+[DefaultPlayerName:W]+70)
Y=-42r
MouseOverAction=[!SetOption PlayerBoth MeterStyle MusicStyle2][!SetOption MusicBox3 SolidColor #Color1#,250][PLAY #@#01.WAV]
MouseLeaveAction=[!SetOption PlayerBoth  MeterStyle MusicStyle1][!SetOption MusicBox3 SolidColor #Color3#,160]
LeftMouseUpAction=[!CommandMeasure PlDe "Play"][!CommandMeasure PlSe "Play"][!DeactivateConfig]
DynamicVariables=1

[DefaultPlayerName]
Meter=String
MeterStyle=MusicStyle1
FontSize=15
StringEffect=None
StringAlign=Left
X=([MusicBox1:X]+5)
Y=-03r
Text=#PlDe#

[SecondaryPlayerName]
Meter=String
MeterStyle=MusicStyle1
FontSize=15
StringEffect=None
StringAlign=Left
X=20r
Y=45r
Text=#PlSe#
DynamicVariables=1

[PlayerBoth]
Meter=String
MeterStyle=MusicStyle1
FontSize=15
StringEffect=None
StringAlign=Left
X=([DefaultPlayerName:X]+[DefaultPlayerName:W]+78)
Y=-42r
Text=Both
DynamicVariables=1
;------
