[MusicVol100]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 100"]
W=10
H=12
X=88r
Y=4r

[MusicVol95]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 95"]
W=10
H=12
X=10r
Y=r

[MusicVol90]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 90"]
W=10
H=12
X=10r
Y=r

[MusicVol85]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 85"]
W=10
H=12
X=10r
Y=r

[MusicVol80]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 80"]
W=10
H=12
X=10r
Y=r

[MusicVol75]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 75"]
W=10
H=12
X=10r
Y=r

[MusicVol70]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 70"]
W=10
H=12
X=10r
Y=r

[MusicVol65]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 65"]
W=10
H=12
X=10r
Y=r

[MusicVol60]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 60"]
W=10
H=12
X=10r
Y=r

[MusicVol55]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 55"]
W=10
H=12
X=10r
Y=r

[MusicVol50]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 50"]
W=10
H=12
X=10r
Y=r

[MusicVol45]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 45"]
W=10
H=12
X=10r
Y=r

[MusicVol40]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 40"]
W=10
H=12
X=10r
Y=r

[MusicVol35]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 35"]
W=10
H=12
X=10r
Y=r

[MusicVol30]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 30"]
W=10
H=12
X=10r
Y=r

[MusicVol25]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 25"]
W=10
H=12
X=10r
Y=r

[MusicVol20]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 20"]
W=10
H=12
X=10r
Y=r

[MusicVol15]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 15"]
W=10
H=12
X=10r
Y=r

[MusicVol10]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 10"]
W=10
H=12
X=10r
Y=r

[MusicVol5]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetVolume 5"]
W=10
H=12
X=10r
Y=r
;--
[MusicPos100]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 100"]
W=15
H=12
X=-290r
Y=-17r

[MusicPos95]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 95"]
W=15
H=12
X=15r
Y=r

[MusicPos90]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 90"]
W=15
H=12
X=15r
Y=r

[MusicPos85]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 85"]
W=15
H=12
X=15r
Y=r

[MusicPos80]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 80"]
W=15
H=12
X=15r
Y=r

[MusicPos75]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 75"]
W=15
H=12
X=15r
Y=r

[MusicPos70]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 70"]
W=15
H=12
X=15r
Y=r

[MusicPos65]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 65"]
W=15
H=12
X=15r
Y=r

[MusicPos60]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 60"]
W=15
H=12
X=15r
Y=r

[MusicPos55]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 55"]
W=15
H=12
X=15r
Y=r

[MusicPos50]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 50"]
W=15
H=12
X=15r
Y=r

[MusicPos45]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 45"]
W=15
H=12
X=15r
Y=r

[MusicPos40]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 40"]
W=15
H=12
X=15r
Y=r

[MusicPos35]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 35"]
W=15
H=12
X=15r
Y=r

[MusicPos30]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 30"]
W=15
H=12
X=15r
Y=r

[MusicPos25]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 25"]
W=15
H=12
X=15r
Y=r

[MusicPos20]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 20"]
W=15
H=12
X=15r
Y=r

[MusicPos15]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 15"]
W=15
H=12
X=15r
Y=r

[MusicPos10]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 10"]
W=15
H=12
X=15r
Y=r

[MusicPos5]
Meter=Image
SolidColor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "PlayerTitle" "SetPosition 5"]
W=15
H=12
X=15r
Y=r