[TextStyle1]
FontColor=#Color1#,255
FontEffectColor=0,0,0,80
StringEffect=BORDER
StringStyle=NORMAL
FontFace=#Font2#
AntiAlias=1

[TextStyle2]
FontColor=#Color1#,255
FontEffectColor=255,0,0,30
StringEffect=BORDER
StringStyle=NORMAL
FontFace=#Font1#
AntiAlias=1

[TextStyle3]
FontColor=#Color3#,250
FontEffectColor=0,0,0,120
StringEffect=BORDER
StringStyle=NORMAL
FontFace=#Font1#
AntiAlias=1

[BarText]
FontColor=#Color4#,255
FontEffectColor=#Color1#,80
StringEffect=BORDER
StringStyle=NORMAL
FontFace=#Font2#
AntiAlias=1