[Variables]
Color1=255,255,255
Color2=218,165,28
Color3=225,0,0
Color4=0,0,0
;---Skin Backgrounds
BackGround=20,20,20,1
HoverGround=20,20,20,100
;---Transparency level with max of 255 for clickable Images
StaticAlpha=255
HoverAlpha=200
;---Hoverable meters backgrounds
StaticBack=40,40,40,80
HoverBack=50,50,50,100
;---
Font1=Cyberverse Condensed
Font2=Autobus
;---
Version=1.1
LastUpdate=12-12-2018
VersionCode=20181212
;----------
SkinLink=https://www.deviantart.com/sparkshredder/art/Bumblebee-Rainmeter-Skin-775793592
;https://www.deviantart.com/sparkshredder/art/Cybertronians-Rainmeter-Skin-767683472
;----------
;Amount by which system volume changes per click
VolChange=5
;----------
Letters=Auto
;-Defne Leters=Auto to let the skin automatically detect Drive letters
;-Define Letters=Uset to show drives of your choice decribed below.
;-If there are less than 4 drives on your device, co-responding meters will be hidden
;-Same for variables left blank while using Letters=User, while Variables empty, start from Drive6 to above
;-If there are less than 4 drives while using Auto, removable disks will be shown in empty meters, whenever connected
; while User will show mentioned Letters only.
Drive1=C:
Drive2=D:
Drive3=E:
Drive4=F:
Drive5=
Drive6=
; Be sure to Put ':' after Drive Letter
;----------
RSToggle=10
;-Time in about secs for Ram-Swap info to toggle
;----------
;----------
LaunchName1= HTML Folder
LaunchPath1=F:\Docs\HTML

LaunchName2= SparkShredder HTML
LaunchPath2=F:\Docs\HTML\SparkShredder

LaunchName3=WallPapers
LaunchPath3=F:\A.O.M\Wallpapers

LaunchName4= My Downloads
LaunchPath4=E:\Downloads

LaunchName5= Sys Downloads
LaunchPath5=C:\Users\Rajnoor Brar\Downloads\MEmu Download

LaunchName6= Documents
LaunchPath6=C:\Users\Rajnoor Brar\Documents
;----------
PlayerName=CAD
PlayerPath=C:\Program Files (x86)\MusicBee\MusicBee.exe
;;Up for single player,, below for double
;Player 1 has higher priority, in case they run together, rest depends on their playing, paused, stopped condition.
Player1Name=CAD
Player1Path=C:\Program Files (x86)\MusicBee\MusicBee.exe

Player2Name=AIMP
Player2Path=C:\Program Files (x86)\AIMP\aimp.exe

;---