[Rainmeter]
Update=100
DefaultUpdateDivider=10
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=System Volume | Speaker Icon instantly Mutes or Unmutes the Volume | Click Filled Bar to decrease volume by 'Fixed' amount and Empty Bar to Increase the Same | Edit Variables to change the 'Fixed' Amount
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[Win7Audio]
Measure=Plugin
Plugin=Win7AudioPlugin
IfBelowValue=0
IfBelowAction=[!SetOption VolSpeaker ImageName "#@#Images\VolMute.png"][!SetOption CurrentVol Text "Muted"]
IfAboveValue=-1
IfAboveAction=[!SetOption VolSpeaker ImageName "#@#Images\VolUnMute.png"][!SetOption CurrentVol Text "Current Volume : %1%"]
[Win7AudioCalc]
Measure=Calc
Formula=Win7Audio
Substitute="-1":"0"

[VolUpCalc]
Measure=Calc
Formula=Win7Audio+#VolChange#
Substitute=

[VolDownCalc]
Measure=Calc
Formula=Win7Audio-#VolChange#
Substitute="-1":"0","-2":"0","-3":"0","-4":"0","-5":"0"

[VolBarWidth]
Measure=Calc
Formula=Win7Audio/100*200
Substitute="-1.5":"0"

[VolHead]
Meter=Shape
Shape=Line 0,0,250,0 | Stroke Color #color2# | StrokeWidth 2
X=0
Y=0

[VolBg]
Meter=Shape
Shape=Rectangle 0,5,250,55 | StrokeWidth 0 | Extend VolBgFill
VolBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption VolBg VolBgFill "Fill Color #HoverGround#"][!UpdateMeter VolBg][!ShowMeterGroup VolInfo][!Redraw]
MouseLeaveAction=[!SetOption VolBg VolBgFill "Fill Color #BackGround#"][!UpdateMeter VolBg][!HideMeterGroup VolInfo][!Redraw]
X=r
Y=r

[VolSpeaker]
Meter=Image
ImageName=#@#Images\VolUnmute.png
Solidcolor=0,0,0,1
LeftMouseUpAction=[!CommandMeasure "Win7Audio" "ToggleMute"]
MouseOverAction=[!SetOption VolAction Text "Toggle Mute"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption VolAction Text ""][!UpdateMeter *][!Redraw]
X=5r
Y=10r

[VolAction]
Meter=String
MeterStyle=TextStyle1
MeasureName=Win7Audio
MeasureName2=VolUpCalc
MeasureName3=VolDownCalc
StringAlign=Right
FontFace=Ariel Narrow
FontSize=8
Group=VolInfo
Hidden=1
X=235r
Y=25r

[CurrentVol]
Meter=String
MeterStyle=TextStyle1
MeasureName=Win7AudioCalc
Text=Current Volume : %1%
StringAlign=Left
FontFace=Ariel Narrow
FontSize=8
Group=VolInfo
Hidden=1
X=-235r
Y=r

[VolumeBar]
Meter=Image
SolidColor=200,200,200,190
BarOrientation=Horizontal
LeftMouseUpAction=[!CommandMeasure "Win7Audio" "ChangeVolume -#VolChange#"][!UpdateMeter *][!Redraw]
MouseOverAction=[!SetOption VolAction Text "Set Volume : %3%"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption VolAction Text ""][!UpdateMeter *][!Redraw]
DynamicVariables=1
W=[VolBarWidth]
H=8
X=40r
Y=-18r

[VolumeBarBg]
Meter=Image
SolidColor=100,100,100,170
BarOrientation=Horizontal
LeftMouseUpAction=[!CommandMeasure "Win7Audio" "ChangeVolume +#VolChange#"][!UpdateMeter *][!Redraw]
MouseOverAction=[!SetOption VolAction Text "Set Volume : %2%"][!UpdateMeter *][!Redraw]
MouseLeaveAction=[!SetOption VolAction Text ""][!UpdateMeter *][!Redraw]
DynamicVariables=1
W=(200-[VolBarWidth])
H=8
X=R
Y=r
