[Rainmeter]
Update=100
DefaultUpdateDivider=10
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Toggles between Ram and Swap info. | Click icon to toggle instantly to Ram/Swap | Edit Variables to change toggle interval
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[MeasureRamTotal]
Measure=PhysicalMemory
Total=1
UpdateDivider=-1

[MeasureRamUsage]
Measure=PhysicalMemory
UpdateDivider=20

[MeasureRamPercent]
Measure=Calc
Formula=(MeasureRamUsage/MeasureRamTotal)*100
MaxValue=100

[MeasureSwapTotal]
Measure=SwapMemory
Total=1
UpdateDivider=-1

[MeasureSwapUsage]
Measure=SwapMemory
UpdateDivider=20

[MeasureSwapPercent]
Measure=Calc
Formula=(MeasureSwapUsage/MeasureSwapTotal)*100
MaxValue=100

[RamShow]
Measure=Calc
Formula=RamShow+1
IfCondition=(RamShow = #RSToggle#)
IfTrueAction=[!DisableMeasure RamShow][!ShowMeterGroup Ram][!SetOption RamIco ImageTint "#Color2#"][!HideMeterGroup Swap][!SetOption SwapIco ImageTint "#Color1#"][!UpdateMeter *][!Redraw][!EnableMeasure SwapShow]
Disabled=1

[SwapShow]
Measure=Calc
Formula=SwapShow+1
IfCondition=(SwapShow = #RSToggle#)
IfTrueAction=[!DisableMeasure SwapShow][!ShowMeterGroup Swap][!SetOption SwapIco ImageTint "#Color2#"][!HideMeterGroup Ram][!SetOption RamIco ImageTint "#Color1#"][!UpdateMeter *][!Redraw][!EnableMeasure RamShow]
;---

[MemoryHead]
Meter=Shape
Shape=Line 0,0,280,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[MemoryBg]
Meter=Shape
Shape=Rectangle 0,4,280,100 | Extend MemoryBgFill | StrokeWidth 0
Shape2=Line 30,10,30,100 | Stroke Color #Color2#,255
Shape3=Line 30,38,2,38 | Stroke Color #Color2#,255
Shape4=Line 30,68,2,68 | Stroke Color #Color2#,255
MemoryBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption MemoryBg MemoryBgFill "Fill Color #HoverGround#"][!UpdateMeter MemoryBg][!Redraw]
MouseLeaveAction=[!SetOption MemoryBg MemoryBgFill "Fill Color #BackGround#"][!UpdateMeter MemoryBg][!Redraw]
X=r
Y=r

[RAMBar]
Meter=Bar
MeasureName=MeasureRAMPercent
BarColor=#color2#
SolidColor=80,80,80,100
BarOrientation=Horizontal
Group=Ram
W=220
H=20
X=45r
Y=10r

[RAM]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureRAMPercent
StringEffect=none
FontColor=#Color4#
Text=RAM : %1%
FontSize=14
Group=Ram
X=5r
Y=r

[RAMTotal]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureRAMTotal
Text=Total Ram : %1
FontSize=12
AutoScale=1
Group=Ram
W=225
H=20
X=-5r
Y=30r

[RAMUsed]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureRAMUsage
Text=Used Ram : %1
FontSize=12
Autoscale=1
Group=Ram
X=r
Y=25r

;--
[SWAPBar]
Meter=Bar
MeasureName=MeasureSWAPPercent
BarColor=#color2#
SolidColor=80,80,80,100
BarOrientation=Horizontal
Group=Swap
Hidden=1
W=220
H=20
X=r
Y=-55r

[SWAP]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureSWAPPercent
StringEffect=none
FontColor=#Color4#
Text=SWAP : %1%
FontSize=14
Group=Swap
Hidden=1
X=5r
Y=r

[SWAPTotal]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureSWAPTotal
Text=Total SWAP : %1
FontSize=12
AutoScale=1
Group=Swap
Hidden=1
W=225
H=20
X=-5r
Y=30r

[SWAPUsed]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureSWAPUsage
Text=Used SWAP : %1
FontSize=12
Autoscale=1
Group=Swap
Hidden=1
X=r
Y=25r
;----
[RamIco]
Meter=Image
ImageName=#@#Images\ram.png
SolidColor=0,0,0,1
ImageTint=#Color2#
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption RamIco ImageAlpha #HoverAlpha#][!UpdateMeter RamIco][!Redraw]
MouseLeaveAction=[!SetOption RamIco ImageAlpha #StaticAlpha#][!UpdateMeter RamIco][!Redraw]
LeftMouseUpAction=[!DisableMeasure RamShow][!ShowMeterGroup Ram][!SetOption RamIco ImageTint "#Color2#"][!HideMeterGroup Swap][!SetOption SwapIco ImageTint "#Color1#"][!UpdateMeter *][!Redraw][!EnableMeasure SwapShow]
W=20
H=20
X=-40r
Y=-53r

[SwapIco]
Meter=Image
ImageName=#@#Images\pagefile.png
SolidColor=0,0,0,1
ImageTint=#Color1#
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption SwapIco ImageAlpha #HoverAlpha#][!UpdateMeter SwapIco][!Redraw]
MouseLeaveAction=[!SetOption SwapIco ImageAlpha #StaticAlpha#][!UpdateMeter SwapIco][!Redraw]
LeftMouseUpAction=[!DisableMeasure SwapShow][!ShowMeterGroup Swap][!SetOption SwapIco ImageTint "#Color2#"][!HideMeterGroup Ram][!SetOption RamIco ImageTint "#Color1#"][!UpdateMeter *][!Redraw][!EnableMeasure RamShow]
W=20
H=20
X=r
Y=30r
