[Rainmeter]
Update=100
DefaultUpdateDivider=10
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Thin Bar to Show Battery Percentage | ShutDown, Restart, Hibernate with 5 sec countdown/ Can be Stopped | Lock Instantly | Refresh : LeftClick to just Refresh all Skins, RightClick to Rescan all Skin folders as well
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[ShutDownCounter]
Measure=Calc
Formula=ShutDownCounter+1
IfEqualValue=6
IfEqualAction=[!HideMeterGroup ShutDown][!ShowMeterGroup Controls][!DisableMeasure ShutDownCounter][%windir%\System32\shutdown.exe -s -t 00]
Disabled=1

[CounterShutDown]
Measure=Calc
Formula=5-ShutDownCounter

[RestartCounter]
Measure=Calc
Formula=RestartCounter+1
IfEqualValue=6
IfEqualAction=[!HideMeterGroup Restart][!ShowMeterGroup Controls][!DisableMeasure RestartCounter][%windir%\System32\shutdown.exe -r -t 00]
Disabled=1

[CounterRestart]
Measure=Calc
Formula=5-RestartCounter

[HibernateCounter]
Measure=Calc
Formula=HibernateCounter+1
IfEqualValue=6
IfEqualAction=[!HideMeterGroup Hibernate][!ShowMeterGroup Controls][!DisableMeasure HibernateCounter][rundll32.exe powrprof.dll, SetSuspendState 0,1,0]
Disabled=1

[CounterHibernate]
Measure=Calc
Formula=5-HibernateCounter

[MeasureCharger]
Measure=Plugin
Plugin=PowerPlugin
PowerState=ACLine
IfAboveValue=0
IfAboveAction=[!SetOption MeterBattery Solidcolor 0,180,0,230][!UpdateMeter MeterBattery][!Redraw]
IfBelowValue=1
IfBelowAction=[!SetOption MeterBattery Solidcolor 80,80,80,100][!UpdateMeter MeterBattery][!Redraw]

[MeasureBattery]
Measure=Plugin
Plugin=PowerPlugin
PowerState=PERCENT
IfBelowValue=21
IfBelowAction=[!SetOption MeterBattery BarColor #Color3#][!UpdateMeter MeterBattery][!Redraw]
IfAboveValue=20
IfAboveAction=[!SetOption MeterBattery BarColor #Color2#][!UpdateMeter MeterBattery][!Redraw]
UpdateDivider=20

[PowerHead]
Meter=Shape
Shape=Line 0,0,250,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[PowerBg]
Meter=Shape
Shape=Rectangle 0,5,250,45 | Extend PowerBgFill | StrokeWidth 0
PowerBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption PowerBg PowerBgFill "Fill Color #HoverGround#"][!UpdateMeter PowerBg][!Redraw]
MouseLeaveAction=[!SetOption PowerBg PowerBgFill "Fill Color #BackGround#"][!UpdateMeter PowerBg][!Redraw]
X=r
Y=r

[ShutDown]
Meter=Image
ImageName=#@#Images\Shutdown.png
ImageTint=#Color1#
Solidcolor=0,0,0,1
LeftMouseUpAction=[!HideMeterGroup Controls][!ShowMeterGroup ShutDown][!EnableMeasure ShutDownCounter]
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption ShutDown ImageAlpha #HoverAlpha#][!UpdateMeter ShutDown][!Redraw]
MouseLeaveAction=[!SetOption ShutDown ImageAlpha #StaticAlpha#][!UpdateMeter ShutDown][!Redraw]
Group=Controls
W=30
H=30
X=10r
Y=10r

[Restart]
Meter=Image
ImageName=#@#Images\Restart.png
ImageTint=#Color1#
Solidcolor=0,0,0,1
LeftMouseUpAction=[!HideMeterGroup Controls][!ShowMeterGroup Restart][!EnableMeasure RestartCounter]
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption Restart ImageAlpha #HoverAlpha#][!UpdateMeter Restart][!Redraw]
MouseLeaveAction=[!SetOption Restart ImageAlpha #StaticAlpha#][!UpdateMeter Restart][!Redraw]
Group=Controls
W=30
H=30
X=50r
Y=r

[Hibernate]
Meter=Image
ImageName=#@#Images\Hibernate.png
ImageTint=#Color1#
Solidcolor=0,0,0,1
LeftMouseUpAction=[!HideMeterGroup Controls][!ShowMeterGroup Hibernate][!EnableMeasure HibernateCounter]
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption Hibernate ImageAlpha #HoverAlpha#][!UpdateMeter Hibernate][!Redraw]
MouseLeaveAction=[!SetOption Hibernate ImageAlpha #StaticAlpha#][!UpdateMeter Hibernate][!Redraw]
Group=Controls
W=30
H=30
X=50r
Y=r

[Lock]
Meter=Image
ImageName=#@#Images\Lock.png
ImageTint=#Color1#
Solidcolor=0,0,0,1
LeftMouseUpAction=[rundll32.exe user32.dll LockWorkStation]
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption Lock ImageAlpha #HoverAlpha#][!UpdateMeter Lock][!Redraw]
MouseLeaveAction=[!SetOption Lock ImageAlpha #StaticAlpha#][!UpdateMeter Lock][!Redraw]
Group=Controls
W=30
H=30
X=50r
Y=r

[Refresh]
Meter=Image
ImageName=#@#Images\Refresh.png
ImageTint=#Color1#
Solidcolor=0,0,0,1
LeftMouseUpAction=[!Refresh *]
RightMouseUpAction=[!RefreshApp]
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption Refresh ImageAlpha #HoverAlpha#][!UpdateMeter Refresh][!Redraw]
MouseLeaveAction=[!SetOption Refresh ImageAlpha #StaticAlpha#][!UpdateMeter Refresh][!Redraw]
Group=Controls
W=30
H=30
X=50r
Y=r

[ShutDownActive]
Meter=String
MeasureName=CounterShutDown
MeterStyle=TextStyle1
Text=ShutDown in %1 secs
Hidden=1
Group=ShutDown
X=-195r
Y=5r

[ShutDownCancel]
Meter=String
MeterStyle=TextStyle1
StringAlign=Right
Text=Cancel ShutDown
SolidColor=0,0,0,1
LeftMouseUpAction=[!HideMeterGroup ShutDown][!ShowMeterGroup Controls][!DisableMeasure ShutDownCounter]
Hidden=1
Group=ShutDown
X=220r
Y=r

[RestartActive]
Meter=String
MeasureName=CounterRestart
MeterStyle=TextStyle1
Text=Restarting in %1 secs
Hidden=1
Group=Restart
X=-220r
Y=r

[RestartCancel]
Meter=String
MeterStyle=TextStyle1
StringAlign=Right
Text=Cancel Restart
SolidColor=0,0,0,1
LeftMouseUpAction=[!HideMeterGroup Restart][!ShowMeterGroup Controls][!DisableMeasure RestartCounter]
Hidden=1
Group=Restart
X=220r
Y=r

[HibernateActive]
Meter=String
MeasureName=CounterHibernate
MeterStyle=TextStyle1
Text=Hibernating in %1 secs
Hidden=1
Group=Hibernate
X=-220r
Y=r

[HibernateCancel]
Meter=String
MeterStyle=TextStyle1
StringAlign=Right
Text=Cancel Hibernate
SolidColor=0,0,0,1
LeftMouseUpAction=[!HideMeterGroup Hibernate][!ShowMeterGroup Controls][!DisableMeasure HibernateCounter]
Group=Hibernate
Hidden=1
X=220r
Y=r

[MeterBattery]
Meter=Bar
MeasureName=MeasureBattery
BarColor=#color2#
SolidColor=80,80,80,100
BarOrientation=Horizontal
X=0
Y=0
W=250
H=4