[Rainmeter]
Update=100
DefaultUpdateDivider=10
OnWakeAction=[!Refresh]
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Current Network Name | LAN\WAN IP Address | NetWork Traffic: Upload\ Download
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[MeasureNetIn]
Measure=NetIn
AverageSize=5

[MeasureNetOut]
Measure=NetOut
AverageSize=5

[MeasureLan]
Measure=Plugin
Plugin=SysInfo
SysInfoType=IP_ADDRESS
Substitute=" ":"","":"---"
SysInfoData=1

[MeasureWan]
Measure=Webparser
Url=http://checkip.dyndns.org
RegExp="(?siU)Address: (.*)</body>"
Substitute=" ":"","":"---"
UpdateRate=300
StringIndex=1

[MeasureSSID]
Measure=Plugin
Plugin=WiFiStatus
WiFiInfoType=SSID
WiFiIntfID=0
Substitute="-1":"Not Connected"
OnChangeAction=[!Refresh]
UpdateDivider=20

[NetIn]
Measure=NetIn
AverageSize=5

[NetOut]
Measure=NetOut
AverageSize=5

[NetHead]
Meter=Shape
Shape=Line 0,0,280,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[NetBg]
Meter=Shape
Shape=Rectangle 0,4,280,100 | Extend NetBgFill | StrokeWidth 0
NetBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption NetBg NetBgFill "Fill Color #HoverGround#"][!UpdateMeter NetBg][!Redraw]
MouseLeaveAction=[!SetOption NetBg NetBgFill "Fill Color #BackGround#"][!UpdateMeter NetBg][!Redraw]
X=r
Y=r

[SSID]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureSSID
Text=%1
FontSize=12
StringAlign=Center
ClipString=1
X=140r
Y=5r
W=260
H=25

[NetSeparate1]
Meter=Shape
Shape=Line 0,0,0,40 | Stroke Color #Color2# | StrokeWidth 1
X=r
Y=23r

[LanName]
Meter=String
MeterStyle=TextStyle1
Text=LAN
FontSize=10
StringAlign=Center
X=-70r
Y=4r

[LanId]
Meter=String
MeasureName=MeasureLan
MeterStyle=TextStyle1
FontSize=10
StringAlign=Center
X=r
Y=20r
W=120
H=20

[WanName]
Meter=String
MeterStyle=TextStyle1
Text=WAN
FontSize=10
StringAlign=Center
X=140r
Y=-20r

[WanId]
Meter=String
MeasureName=MeasureWan
MeterStyle=TextStyle1
FontSize=10
StringAlign=Center
X=r
Y=20r
W=120
H=20

[NetSeparate2]
Meter=Shape
Shape=Line 0,0,240,0 | Stroke Color #color2#
Shape2=Line 120,2,120,26 | Stroke Color #Color2#
X=-190r
Y=22r

[NetUp]
Meter=Image
ImageName=#@#Images\NetUp.png
X=95r
Y=5r
W=15
H=20

[UpSpeed]
Meter=String
MeasureName=NetOut
MeterStyle=TextStyle1
StringAlign=Right
FontSize=12
Text=%1b/s
AutoScale=1
X=-5r
Y=2r

[NetDown]
Meter=Image
ImageName=#@#Images\NetDown.png
X=35r
Y=-2r
W=15
H=20

[DownSpeed]
Meter=String
MeasureName=NetIn
MeterStyle=TextStyle1
StringAlign=Left
FontSize=12
Text=%1b/s
AutoScale=1
X=20r
Y=2r
