[Rainmeter]
Update=100
DefaultUpdateDivider=10
AccurateText=1

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Displays Simple CPU Stats: | Average Cpu Usage of all cores | Processor Name | Max Clock Speed of CPU
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[MeasureCPUName]
Measure=Registry
RegHKey=HKEY_LOCAL_MACHINE
RegKey=HARDWARE\DESCRIPTION\System\CentralProcessor\0
RegValue=ProcessorNameString
Substitute="  ":""
UpdateDivider=-1

[MeasureCPUSpeed]
Measure=Registry
RegHKey=HKEY_LOCAL_MACHINE
RegKey=HARDWARE\DESCRIPTION\System\CentralProcessor\0
RegValue=~MHz
UpdateDivider=-1

[MeasureCPU]
Measure=CPU

[CPUHead]
Meter=Shape
Shape=Line 0,0,280,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[CPUBg]
Meter=Shape
Shape=Rectangle 0,4,280,100 | Extend CPUBgFill | StrokeWidth 0
Shape2=Line 30,10,30,100 | Stroke Color #Color2#,255
Shape3=Line 30,38,2,38 | Stroke Color #Color2#,255
;Shape4=Line 30,68,2,68 | Stroke Color #Color2#,255
CPUBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption CPUBg CPUBgFill "Fill Color #HoverGround#"][!UpdateMeter CPUBg][!Redraw]
MouseLeaveAction=[!SetOption CPUBg CPUBgFill "Fill Color #BackGround#"][!UpdateMeter CPUBg][!Redraw]
X=r
Y=r

[CPUBar]
Meter=Bar
MeasureName=MeasureCPU
BarColor=#color2#
SolidColor=80,80,80,100
BarOrientation=Horizontal
W=220
H=20
X=45r
Y=10r

[CPU]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureCPU
StringEffect=none
FontColor=#Color4#
Text=CPU : %1%
FontSize=14
X=5r
Y=r

[CPUName]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureCPUName
Text=%1
FontSize=12
Clipstring=1
W=225
H=20
X=-5r
Y=30r

[CpuClockSpeed]
Meter=String
MeterStyle=TextStyle1
MeasureName=MeasureCPUSpeed
Text=Max Clock Speed : %1 GHz
FontSize=12
Scale=1000
NumOfDecimals=2
X=r
Y=25r

;---
[CPUIco]
Meter=Image
ImageName=#@#Images\cpu.png
SolidColor=0,0,0,1
ImageTint=#Color2#
ImageAlpha=#StaticAlpha#
MouseOverAction=[!SetOption CPUIco ImageAlpha #HoverAlpha#][!UpdateMeter CPUIco][!Redraw]
MouseLeaveAction=[!SetOption CPUIco ImageAlpha #StaticAlpha#][!UpdateMeter CPUIco][!Redraw]
W=20
H=20
X=-40r
Y=-53r
