[Rainmeter]
Update=100
DefaultUpdateDivider=10
AccurateText=1
ContextTitle=#PlayerContext#
ContextAction=[!CommandMeasure PlayerTitle "OpenPlayer"]

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Cover Art, Track Name, Artist, Album , Elapsed Duration, Total Duration | Progress Bar, Volume Bar : Clickable to Change | Media Button : Previous, Play/Pause , Stop, Next | Edit Variables for PlayerName as well as Path
Version=1.0
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin

[PlayerTitle]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=TITLE
PlayerPath=#PlayerPath#
Substitute="":"N/A"

[ArtistCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=ARTIST
Substitute="":"N/A"

[AlbumCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=ALBUM
Substitute="":"N/A"

[PositionCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=POSITION

[DurationCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=DURATION

[StatusCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=Status
IfEqualValue=0
IfEqualAction=[!HideMeterGroup Player][!ShowMeterGroup Activate][!UpdateMeter *][!SetVariable PlayerContext "Open Player"][!Redraw]
IfAboveValue=0
IfAboveAction=[!ShowMeterGroup Player][!HideMeterGroup Activate][!UpdateMeter *][!SetVariable PlayerContext "Bring Player to Top"][!Redraw]

[ProgressCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=PROGRESS

[RepeatSet]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=REPEAT

[ShuffleSet]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=SHUFFLE

[CoverArtCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=COVER
UpdateDivider=50
Substitute="":"#@#Images/FileUnavailable.png"

[MusicVolumeCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=VOLUME

[StateSet]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=STATE
Substitute="0":"4","1":";","2":"4"

[MusicHead]
Meter=Shape
Shape=Line 0,0,320,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[MusicBg]
Meter=Shape
Shape=Rectangle 0,4,320,130 | Extend MusicBgFill | StrokeWidth 0
MusicBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption MusicBg MusicBgFill "Fill Color #HoverGround#"][!UpdateMeter MusicBg][!Redraw]
MouseLeaveAction=[!SetOption MusicBg MusicBgFill "Fill Color #BackGround#"][!UpdateMeter MusicBg][!Redraw]
X=r
Y=r

[OpenPlayerText]
Meter=String
MeterStyle=TextStyle3
StringAlign=Center
Fontsize=14
Text=The Player is Currently Inactive
Group=Activate
Hidden=1
X=160r
Y=25r

[OpenPlayerButton]
Meter=String
MeterStyle=TextStyle1
SolidColor=#StaticBack#
StringAlign=Center
Padding=10,5,10,5
Fontsize=13
Text="Open Player"
LeftMouseUpAction=[!CommandMeasure PlayerTitle "OpenPlayer"]
MouseOverAction=[!SetOption OpenPlayerButton SolidColor #HoverBack#][!UpdateMeter OpenPlayerButton][!Redraw]
MouseLeaveAction=[!SetOption OpenPlayerButton SolidColor #StaticBack#][!UpdateMeter OpenPlayerButton][!Redraw]
Group=Activate
Hidden=1
X=r
Y=40r

[CoverArtImage]
Meter=Image
MeasureName=CoverArtCheck
Solidcolor=40,40,40,150
Group=Player
W=70
H=70
X=75r
Y=-60r
Padding=5,5,5,5

[TrackTitleText]
Meter=String
MeterStyle=TextStyle1
MeasureName=PlayerTitle
StringAlign=Right
ClipString=1
FontSize=12
Group=Player
W=210
H=20
X=-10r
Y=5r

[ArtistText]
Meter=String
MeterStyle=TextStyle1
MeasureName=ArtistCheck
StringAlign=Right
ClipString=1
FontSize=12
Group=Player
W=210
H=20
X=r
Y=20r

[AlbumText]
Meter=String
MeterStyle=TextStyle1
MeasureName=AlbumCheck
StringAlign=Right
ClipString=1
FontSize=12
Group=Player
W=210
H=20
X=r
Y=20r

[DurationText]
Meter=String
MeterStyle=TextStyle1
MeasureName=PositionCheck
MeasureName2=DurationCheck
StringAlign=Right
ClipString=1
Text=%1 / %2
FontSize=12
Group=Player
W=210
H=20
X=r
Y=20r

[PlayerProgressBar]
Meter=Bar
MeasureName=ProgressCheck
W=300
H=12
X=-210r
Y=20r
SolidColor=80,80,80,100
BarColor=#color2#,235
BarOrientation=Horizontal
Flip=1
Group=Player

[PlayerVolumeBar]
Meter=Bar
MeasureName=MusicVolumeCheck
W=200
H=12
X=100r
Y=17r
SolidColor=80,80,80,100
BarColor=#color2#,235
BarOrientation=Horizontal
Flip=1
Group=Player

[Next]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
SolidColor=#Color4#,1
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Next FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Next FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "Next"]
Group=Player
UpdateDivider=9
X=-13r
Y=-4r
Text=":"

[Stop]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Stop FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Stop FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "Stop"]
Group=Player
UpdateDivider=9
X=-25r
Y=r
Text="<"

[Play]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Play FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Play FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "PlayPause"]
Group=Player
UpdateDivider=9
X=-25r
Y=r
Text=[StateSet]

[Previous]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Previous FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Previous FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "Previous"]
Group=Player
UpdateDivider=9
X=-25r
Y=r
Text="9"

@Include3=#@#MusicControls.inc
;--Position and Volume Controls in Additional file, beacuse they are tooo much long enough to interfere in Devlopment progress.
