[Rainmeter]
Update=100
DefaultUpdateDivider=10
AccurateText=1
ContextTitle=#Player1Context#
ContextAction=#Player1Action#
Contexttitle2=#Player2Context#
ContextAction2=#Player2Action#

[Metadata]
Name=Bumblebee
Author=SparkShredder
Information=Cover Art, Track Name, Artist, Album , Elapsed Duration, Total Duration | Progress Bar, Volume Bar : Clickable to Change | Media Button : Previous, Play/Pause , Stop, Next | Edit Variables for PlayerName as well as Path
Version=1.1
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

;----------Variables

@include=#@#Variables.inc

[Variables]
Player1Open=[!CommandMeasure Player1 OpenPlayer]
Player1Close=[!CommandMeasure Player1 ClosePlayer]

Player2Open=[!CommandMeasure Player2 OpenPlayer]
Player2Close=[!CommandMeasure Player2 ClosePlayer]

;----------Meter-Styles

@include2=#@#Styles.inc

;----------Skin
[Player1]
Measure=NowPlaying
PlayerName=#Player1Name#
PlayerPath=#Player1Path#
PlayerType=Status
IfEqualValue=0
IfEqualAction=[!SetVariable Player1Context "Open Player 1"][!SetVariable Player1Action "#Player1Open#"]
IfAboveValue=0
IfAboveAction=[!SetVariable Player1Context "Close Player 1"][!SetVariable Player1Action "#Player1Close#"]

[Player2]
Measure=NowPlaying
PlayerName=#Player2Name#
PlayerPath=#Player2Path#
PlayerType=Status
IfEqualValue=0
IfEqualAction=[!SetVariable Player2Context "Open Player 2"][!SetVariable Player2Action "#Player2Open#"]
IfAboveValue=0
IfAboveAction=[!SetVariable Player2Context "Close Player 2"][!SetVariable Player2Action "#Player2Close#"]

[Player1State]
Measure=NowPlaying
PlayerName=[Player1]
PlayerType=State

[Player2State]
Measure=NowPlaying
PlayerName=[Player2]
PlayerType=State
;--------
IfCondition=(Player2State = 0) & (Player1State = 0) & (Player2 = 1) & (Player1 = 1)
IfTrueAction=[!SetOption PlayerTitle PlayerName "#Player1Name#"][!SetOption PA Text "Player 1"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition2=(Player2State = 0) & (Player1State = 0) & (Player2 = 0) & (Player1 = 1)
IfTrueAction2=[!SetOption PlayerTitle PlayerName "#Player1Name#"][!SetOption PA Text "Player 1"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition3=(Player2State = 0) & (Player1State = 0) & (Player2 = 1) & (Player1 = 0)
IfTrueAction3=[!SetOption PlayerTitle PlayerName "#Player2Name#"][!SetOption PA Text "Player 2"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition4=(Player2State = 0) & (Player1State = 1)
IfTrueAction4=[!SetOption PlayerTitle PlayerName "#Player1Name#"][!SetOption PA Text "Player 1"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition5=(Player2State = 0) & (Player1State = 2)
IfTrueAction5=[!SetOption PlayerTitle PlayerName "#Player1Name#"][!SetOption PA Text "Player 1"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition6=(Player2State = 1) & (Player1State = 0)
IfTrueAction6=[!SetOption PlayerTitle PlayerName "#Player2Name#"][!SetOption PA Text "Player 2"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition7=(Player2State = 1) & (Player1State = 1)
IfTrueAction7=[!SetOption PlayerTitle PlayerName "#Player1Name#"][!SetOption PA Text "Player 1"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition8=(Player2State = 1) & (Player1State = 2)
IfTrueAction8=[!SetOption PlayerTitle PlayerName "#Player2Name#"][!SetOption PA Text "Player 2"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition9=(Player2State = 2) & (Player1State = 0)
IfTrueAction9=[!SetOption PlayerTitle PlayerName "#Player2Name#"][!SetOption PA Text "Player 2"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition10=(Player2State = 2) & (Player1State = 1)
IfTrueAction10=[!SetOption PlayerTitle PlayerName "#Player1Name#"][!SetOption PA Text "Player 1"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition11=(Player2State = 2) & (Player1State = 2)
IfTrueAction11=[!SetOption PlayerTitle PlayerName "#Player1Name#"][!UpdateMeasure PlayerTitle][!Redraw]
;------------------------
IfCondition12=(Player2 = 0) & (Player1 = 0)
IfTrueAction12=[!HideMeterGroup Player][!ShowMeterGroup Activate]
IfFalseAction12=[!ShowMeterGroup Player][!HideMeterGroup Activate]

[PlayerTitle]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=TITLE
PlayerPath=#PlayerPath#
Substitute="":"N/A"

[ArtistCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=ARTIST
Substitute="":"N/A"

[AlbumCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=ALBUM
Substitute="":"N/A"

[PositionCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=POSITION

[DurationCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=DURATION

[ProgressCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=PROGRESS

[RepeatSet]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=REPEAT

[ShuffleSet]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=SHUFFLE

[CoverArtCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=COVER
UpdateDivider=50
Substitute="":"#@#Images/FileUnavailable.png"

[MusicVolumeCheck]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=VOLUME

[StateSet]
Measure=NowPlaying
PlayerName=[PlayerTitle]
PlayerType=STATE
Substitute="0":"4","1":";","2":"4"

[MusicHead]
Meter=Shape
Shape=Line 0,0,320,0 | Stroke Color #Color2#,255 | StrokeWidth 2
X=0
Y=0

[MusicBg]
Meter=Shape
Shape=Rectangle 0,4,320,135 | Extend MusicBgFill | StrokeWidth 0
MusicBgFill=Fill Color #BackGround#
MouseOverAction=[!SetOption MusicBg MusicBgFill "Fill Color #HoverGround#"][!UpdateMeter MusicBg][!Redraw]
MouseLeaveAction=[!SetOption MusicBg MusicBgFill "Fill Color #BackGround#"][!UpdateMeter MusicBg][!Redraw]
X=r
Y=r

[OpenPlayerText]
Meter=String
MeterStyle=TextStyle3
StringAlign=Center
Fontsize=14
Text=Both Players are Currently Inactive
Group=Activate
Hidden=1
X=160r
Y=25r

[OpenPlayerButton1]
Meter=String
MeterStyle=TextStyle1
SolidColor=#StaticBack#
StringAlign=Right
Padding=10,5,10,5
Fontsize=13
Text="Open Player 1"
LeftMouseUpAction=[!CommandMeasure Player1 "OpenPlayer"]
MouseOverAction=[!SetOption OpenPlayerButton SolidColor #HoverBack#][!UpdateMeter OpenPlayerButton][!Redraw]
MouseLeaveAction=[!SetOption OpenPlayerButton SolidColor #StaticBack#][!UpdateMeter OpenPlayerButton][!Redraw]
Group=Activate
Hidden=1
X=-10r
Y=40r

[OpenPlayerButton2]
Meter=String
MeterStyle=TextStyle1
SolidColor=#StaticBack#
StringAlign=Left
Padding=10,5,10,5
Fontsize=13
Text="Open Player 2"
LeftMouseUpAction=[!CommandMeasure Player1 "OpenPlayer"]
MouseOverAction=[!SetOption OpenPlayerButton SolidColor #HoverBack#][!UpdateMeter OpenPlayerButton][!Redraw]
MouseLeaveAction=[!SetOption OpenPlayerButton SolidColor #StaticBack#][!UpdateMeter OpenPlayerButton][!Redraw]
Group=Activate
Hidden=1
X=20r
Y=r

[CoverArtImage]
Meter=Image
MeasureName=CoverArtCheck
Solidcolor=40,40,40,150
Group=Player
W=70
H=70
X=65r
Y=-60r
Padding=5,5,5,5

[TrackTitleText]
Meter=String
MeterStyle=TextStyle1
MeasureName=PlayerTitle
StringAlign=Right
ClipString=1
FontSize=12
Group=Player
W=210
H=20
X=-10r
Y=5r

[ArtistText]
Meter=String
MeterStyle=TextStyle1
MeasureName=ArtistCheck
StringAlign=Right
ClipString=1
FontSize=12
Group=Player
W=210
H=20
X=r
Y=20r

[AlbumText]
Meter=String
MeterStyle=TextStyle1
MeasureName=AlbumCheck
StringAlign=Right
ClipString=1
FontSize=12
Group=Player
W=210
H=20
X=r
Y=20r

[DurationText]
Meter=String
MeterStyle=TextStyle1
MeasureName=PositionCheck
MeasureName2=DurationCheck
StringAlign=Right
ClipString=1
Text=%1 / %2
FontSize=12
Group=Player
W=210
H=20
X=r
Y=20r

[PlayerProgressBar]
Meter=Bar
MeasureName=ProgressCheck
W=300
H=12
X=-210r
Y=20r
SolidColor=80,80,80,100
BarColor=#color2#,235
BarOrientation=Horizontal
Flip=1
Group=Player

[PlayerVolumeBar]
Meter=Bar
MeasureName=MusicVolumeCheck
W=200
H=12
X=100r
Y=17r
SolidColor=80,80,80,100
BarColor=#color2#,235
BarOrientation=Horizontal
Flip=1
Group=Player

[Next]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
SolidColor=#Color4#,1
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Next FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Next FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "Next"]
Group=Player
UpdateDivider=9
X=-13r
Y=-4r
Text=":"

[Stop]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Stop FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Stop FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "Stop"]
Group=Player
UpdateDivider=9
X=-25r
Y=r
Text="<"

[Play]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Play FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Play FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "PlayPause"]
Group=Player
UpdateDivider=9
X=-25r
Y=r
Text=[StateSet]

[Previous]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=#Color4#,80
StringEffect=BORDER
FontSize=16
W=25
H=18
StringAlign=Center
FontFace=Webdings
MouseOverAction=[!SetOption Previous FontEffectColor #Color1#,100]
MouseLeaveAction=[!SetOption  Previous FontEffectColor #Color4#,80]
LeftMouseDownAction=[!CommandMeasure PlayerTitle "Previous"]
Group=Player
UpdateDivider=9
X=-25r
Y=r
Text="9"

@Include3=#@#MusicControls.inc
;--Position and Volume Controls in Additional file, beacuse they are tooo much long enough to interfere in Devlopment progress.

[PA]
Meter=String
MeterStyle=TextStyle1
StringAlign=Right
ClipString=1
FontSize=9
Text=Player 1
Group=Player
W=210
H=20
X=310
Y=120