[RainMeter]
Author=Rajnoor Brar
Update=1
AntiAlias=1

[Metadata]
Name=RoboCop Rainmeter Skin
Author=ZakycooL
Information=TargetBox following Mouse Cursor 

[Variables]
Color2=0,128,0


;:=====================Mouse===============Target====================:;
[TextStyle1]
FontColor=#Color2#,255
FontEffectColor=#Color2#,17
StringEffect=NONE
StringStyle=NORMAL
FontFace=SF Transrobotics
AntiAlias=1

[MouseX]
Measure=Plugin
Plugin=MouseXY
Dimension=X
 
[MouseY]
Measure=Plugin
Plugin=MouseXY
Dimension=Y

[ScanTargH]
Meter=Image
W=#workareawidth#
H=1
X=0
Y=[MouseY]
SolidColor=0,0,0,1
SolidColor2=#Color2#,250
GradientAngle=45.0
DynamicVariables=1
Hidden=0
Update=1

[ScanTargV]
Meter=Image
W=1
H=#workareaheight#
X=[MouseX]
Y=0
SolidColor=0,0,0,1
SolidColor2=#Color2#,250
GradientAngle=45.0
DynamicVariables=1
Hidden=0
Update=1

[TargBox]
Meter=Image
ImageName=#@#Images\files\targ01.png
X=([MouseX]-95/2)
Y=([MouseY]-95/2)
ImageTint=#Color2#
DynamicVariables=1
Hidden=0
Update=1

[TexTXY]
Meter=String
MeterStyle=TextStyle1
FontEffectColor=0,0,0,80
StringEffect=BORDER
FontSize=10
StringAlign=Left
X=([MouseX]+40)
Y=([MouseY]-12)
Text="X_[MouseX]#CRLF#Y_[MouseY]"
DynamicVariables=1
Hidden=0
Update=1

[CountD]
Measure=Calc
Formula=Counter % 2
DynamicVariables=1
UpdateDivider=5
Disabled=0

[DimTarget]
Meter=IMAGE
ImageName=#@#Images\files\dim\[CountD].png
ImageTint=#Color2#,255
X=([MouseX]+25)
Y=([MouseY]-40)
DynamicVariables=1
Hidden=0
Update=1