[RainMeter]
Update=100
DefaultUpdateDivider=10
OnRefreshAction=#ConWallSet#[!ZPos 2]
OnWakeAction=[!UpdateMeasure *][!UpdateMeter *][!Redraw]

[Metadata]
Name=Decepticons Rainmeter Skin
Author=Rajnoor Brar
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

[variables]
@include=#@#\Cybertron.inc
@include2=#@#\Config.inc
@include3=#@#\#Battery#.inc
Config=#@#\Config.inc
Color1=#Concolor1#
Color2=#Concolor2#
Color3=#Concolor3#
ColorPlayerC=#ConPlayerColor#
Saber=consaber
Faction=Autobots
Insignia=conInsignia
Volgroup=vol | Main
V1
V2
PowerGroup=power | Main
P1=none
P2=main
Notegroup=notes | Main
N1=none
N2=main
Drivegroup=drives | Main
D1=none
D2=main
LaunchGroup=launchers | Main
L1=none
L2=main
;----
Latitude=30.9
Longitude=75.85
Region=Punjab
Country=India
;------StartUP-----------------------------
Damage1=Inspecting Damage Taken
Damage1a=Damage Report#CRLF#Armor Mildly Damaged
Damage1b=Damage Report#CRLF#Optical Vision Razor Sharp
Damage1c=Damage Report#CRLF#Audio Receptors Crystal Clear
Damage1d=Damage Report#CRLF#T-COG Functioning
Damage1e=Damage Report#CRLF#Data Drives Unscratched
Damage1f=Overall Stats#CRLF#Ready to Obliterate
Damage2=Damage Report : Uncritical
Damage2a=Armor Mildly Damaged
Damage2b=Optical Vision Razor Sharp
Damage2c=Audio Receptors Crystal Clear
Damage2d=T-COG Functioning
Damage2e=Data Drives Unscratched
;---
Location1=Initiating Navigations
Location1a=Loading Location..
Location1b=Location Identified#CRLF#Earth: #Latitude# , #Longitude#
Location2=Location : #Latitude# , #Longitude# - #Region#, #Country#
;---
ComLink1=Sequencing Universal ComLinks
ComLink1a=Comlinks Established
ComLink2=Communications Established
;---
Battle1=Retrieving Intel on the War
Battle1a=War Intel#CRLF#[BattleCalc]
Battle2=War Intel : [BattleCalc]
;---
Energon1=Observing Energon Level
Energon1a=Energon Build-Up#CRLF##EnergonLevel#
Energon2=Energon Build-Up : #EnergonLevel#
;---
Weapon1=Checking Weapons Systems...
Weapon1a=Weapon Systems#CRLF#[WeaponCalc]
Weapon2=Weapons Stats: [WeaponCalc]
;---
HQ1=Locating HeadQuaters..
HQ1a=Nearest HQ Located
HQ2=HQ CoOrdinates : Pinpointed
;---
Ground1=Accessing Comlink Frequency..
Ground1a=Accessed: Sending Request#CRLF#GroundBridge Teleportation
Ground2=GroundBridge Teleportation Requested
;------StartUP--End---------------

[IntroHead]
FontColor=#Color1#,250
FontEffectColor=0,0,0,100
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=Center
FontFace=Autobus
FontSize=25
X=(1366/2)
Y=205
AntiAlias=1 

[IntroStyle1]
FontColor=0,0,0
FontEffectColor=#color1#,20
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=Left
FontFace=Autobus
FontSize=16
UpdateDivider=1
X=325
Y=R
AntiAlias=1

[IntroStyle1a]
FontColor=#Color2#,230
FontEffectColor=0,0,0,100
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=Left
FontFace=Autobus
FontSize=13
UpdateDivider=1
X=355
Y=R
AntiAlias=1

[IntroStyle2]
FontColor=#Color1#,250
FontEffectColor=0,0,0,200
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=CenterCenter
FontFace=Autobus
FontSize=35
UpdateDivider=1
InlinePattern=#CRLF#(.*)
InlineSetting=Size | 27
w=800
h=450
X=(1366/2)
Y=(768/2)
AntiAlias=1
;=======================================

[Fade]
Measure=Script
ScriptFile=#@#Scripts\Fade.lua
Min=0
Max=255
Step=8
Start=255
MeterName=ONLINE | Insignia0

[IPLocation]
Measure=Plugin
Plugin=WebParser
URL=https://iplocation.com/
RegExp=(?siU)<td class="lat">(.*)</td>.*<td class="lng">(.*)</td>.*<td><span class="country_name">(.*)</span></td>.* <td><span class="region_name">(.*)</span></td>
FinishAction=[!WriteKeyValue Variables Latitude "[IPLat]" "#Config#"][!SetVariable Latitude "[IPlat]"][!WriteKeyValue Variables Longitude "[IPLong]" "#Config#"][!SetVariable Longitude "[IPLong]"][!WriteKeyValue Variables Region "[IPRegion]" "#Config#"][!SetVariable Longitude "[IPLong]"][!WriteKeyValue Variables Country "[IPCountry]" "#Config#"][!SetVariable Country "[IPCountry]"]
UpdateDivider=-1
Group=startup

[IPLat]
Measure=Plugin
Plugin=WebParser
URL=[IPLocation]
StringIndex=1
UpdateDivider=-1
Group=startup

[IPLong]
Measure=Plugin
Plugin=WebParser
URL=[IPLocation]
StringIndex=2
UpdateDivider=-1
Group=startup

[IPCountry]
Measure=Plugin
Plugin=WebParser
URL=[IPLocation]
StringIndex=3
UpdateDivider=-1
Group=startup

[IPRegion]
Measure=Plugin
Plugin=WebParser
URL=[IPLocation]
StringIndex=4
UpdateDivider=-1
Group=startup
;=============
[move00]
Measure=Calc
Formula=move00+(768/30)
DynamicVariables=1
IfEqualValue=384
IfEqualAction=[!PauseMeasure move00][!PauseMeasureGroup startup][!EnableMeasureGroup Main][!ShowMeterGroup Main][!ZPos -2]
UpdateDivider=1
Disabled=1

[ActionTimer]
Measure=Calc
Formula=ActionTimer+1
UpdateDivider=1
;--------
IfCondition=(ActionTimer = 10)
IfTrueAction=[!ShowMeter Online]
IfCondition2=(ActionTimer = 14)
IfTrueAction2=[!SetOption Online MeterStyle "IntroHead"][!ShowMeter Insignia0][!ShowMeter DamageStats]
IfCondition3=(ActionTimer = 16)
IfTrueAction3=[!SetOption DamageStats Text "#Damage1a#"]
IfCondition4=(ActionTimer = 20)
IfTrueAction4=[!SetOption DamageStats Text "#Damage1b#"]
IfCondition5=(ActionTimer = 24)
IfTrueAction5=[!SetOption DamageStats Text "#Damage1c#"]
IfCondition6=(ActionTimer = 28)
IfTrueAction6=[!SetOption DamageStats Text "#Damage1d#"]
IfCondition7=(ActionTimer = 32)
IfTrueAction7=[!SetOption DamageStats Text "#Damage1e#"]
IfCondition8=(ActionTimer = 36)
IfTrueAction8=[!SetOption DamageStats Text "#Damage1f#"]
IfCondition9=(ActionTimer = 40)
IfTrueAction9=[!SetOption DamageStats Text "#Damage2#"][!SetOption DamageStats MeterStyle "IntroStyle1"][!SetOption DamageStats Y "255"]
IfCondition10=(ActionTimer = 41)
IfTrueAction10=[!SetOption DamageStats1 MeterStyle "IntroStyle1a"][!ShowMeter DamageStats1]
IfCondition11=(ActionTimer = 42)
IfTrueAction11=[!SetOption DamageStats2 MeterStyle "IntroStyle1a"][!ShowMeter DamageStats2]
IfCondition12=(ActionTimer = 43)
IfTrueAction12=[!SetOption DamageStats3 MeterStyle "IntroStyle1a"][!ShowMeter DamageStats3]
IfCondition13=(ActionTimer = 44)
IfTrueAction13=[!SetOption DamageStats4 MeterStyle "IntroStyle1a"][!ShowMeter DamageStats4][!ShowMeter Location]
IfCondition14=(ActionTimer = 45)
IfTrueAction14=[!SetOption DamageStats5 MeterStyle "IntroStyle1a"][!ShowMeter DamageStats5]
IfCondition15=(ActionTimer = 46)
IfTrueAction15=[!HideMeter DamageStats5]
IfCondition16=(ActionTimer = 47)
IfTrueAction16=[!HideMeter DamageStats4]
IfCondition17=(ActionTimer = 48)
IfTrueAction17=[!HideMeter DamageStats3][!SetOption Location Text "#Location1a#"]
IfCondition18=(ActionTimer = 49)
IfTrueAction18=[!HideMeter DamageStats2]
IfCondition19=(ActionTimer = 50)
IfTrueAction19=[!HideMeter DamageStats1][!ShowMeter Navigation][!SetOption Navigation MeterStyle "IntroStyle1"]
IfCondition20=(ActionTimer = 52)
IfTrueAction20=[!SetOption Location Text "#Location1b#"]
IfCondition21=(ActionTimer = 56)
IfTrueAction21=[!SetOption Location Text "#Location2#"][!SetOption Location MeterStyle "IntroStyle1"][!ShowMeter ComLinks]
IfCondition22=(ActionTimer = 60)
IfTrueAction22=[!SetOption ComLinks Text "#ComLink1a#"]
IfCondition23=(ActionTimer = 65)
IfTrueAction23=[!SetOption ComLinks Text "#ComLink2#"][!SetOption ComLinks MeterStyle "IntroStyle1"][!ShowMeter BattleStats]
IfCondition24=(ActionTimer = 70)
IfTrueAction24=[!SetOption BattleStats Text "#Battle1a#"]
IfCondition25=(ActionTimer = 75)
IfTrueAction25=[!SetOption BattleStats Text "#Battle2#"][!SetOption BattleStats MeterStyle "IntroStyle1"][!ShowMeter EnergonStats]
IfCondition26=(ActionTimer = 80)
IfTrueAction26=[!SetOption EnergonStats Text "#Energon1a#"]
IfCondition27=(ActionTimer = 85)
IfTrueAction27=[!SetOption EnergonStats Text "#Energon2#"][!SetOption EnergonStats MeterStyle "IntroStyle1"][!ShowMeter WeaponStats]
IfCondition28=(ActionTimer = 90)
IfTrueAction28=[!SetOption WeaponStats Text "#Weapon1a#"]
IfCondition29=(ActionTimer = 95)
IfTrueAction29=[!SetOption WeaponStats Text "#Weapon2#"][!SetOption WeaponStats MeterStyle "IntroStyle1"][!ShowMeter HQLocate]
IfCondition30=(ActionTimer = 100)
IfTrueAction30=[!SetOption HQLocate Text "#HQ1a#"]
IfCondition31=(ActionTimer = 105)
IfTrueAction31=[!SetOption HQLocate Text "#HQ2#"][!SetOption HQLocate MeterStyle "IntroStyle1"][!ShowMeter GroundBridge]
IfCondition32=(ActionTimer = 110)
IfTrueAction32=[!SetOption GroundBridge Text "#Ground1a#"][!ShowMeter CLF][!SetOption CLF MeterStyle "IntroStyle1"]
IfCondition33=(ActionTimer = 115)
IfTrueAction33=[!SetOption GroundBridge Text "#Ground2#"][!SetOption GroundBridge MeterStyle "IntroStyle1"][!SetOption DamageStats FontColor "#color1#"]
IfCondition34=(ActionTimer = 120)
IfTrueAction34=[!HideMeter DamageStats][!SetOption Navigation FontColor "#color1#"][!CommandMeasure Fade Activate(Out)]
IfCondition35=(ActionTimer = 123)
IfTrueAction35=[!HideMeter Navigation][!SetOption Location FontColor "#color1#"]
IfCondition36=(ActionTimer = 126)
IfTrueAction36=[!HideMeter Location][!SetOption ComLinks FontColor "#color1#"]
IfCondition37=(ActionTimer = 129)
IfTrueAction37=[!HideMeter ComLinks][!SetOption BattleStats FontColor "#color1#"]
IfCondition38=(ActionTimer = 132)
IfTrueAction38=[!HideMeter BattleStats][!SetOption EnergonStats FontColor "#color1#"]
IfCondition39=(ActionTimer = 135)
IfTrueAction39=[!HideMeter EnergonStats][!SetOption WeaponStats FontColor "#color1#"]
IfCondition40=(ActionTimer = 138)
IfTrueAction40=[!HideMeter WeaponStats][!SetOption HQLocate FontColor "#color1#"]
IfCondition41=(ActionTimer = 141)
IfTrueAction41=[!HideMeter HQLocate][!SetOption CLF FontColor "#color1#"]
IfCondition42=(ActionTimer = 144)
IfTrueAction42=[!HideMeter CLF][!SetOption GroundBridge FontColor "#color1#"]
IfCondition43=(ActionTimer = 147)
IfTrueAction43=[!HideMeter GroundBridge][!HideMeter ONLINE][!HideMeter Insignia0][!ShowMeter ROLLOUT]
IfCondition44=(ActionTimer = 152)
IfTrueAction44=[!HideMeter ROLLOUT][!SetOption BangOutH InvertMeasure "1"][!EnableMeasure BangOutH]
IfCondition45=(ActionTimer = 162)
IfTrueAction45=[!EnableMeasure move00][!PauseMeasure ActionTimer]

[BangOutH]
Measure=Loop
StartValue=0
EndValue=420
Increment=42
LoopCount=1
UpdateDivider=1
Group=startup

[BlurA]
Meter=Image
SolidColor=0,0,0,220
W=#workareawidth#
H=(768/2)
X=0
Y=(0-[move00])
UpdateDivider=1
DynamicVariables=1

[BlurB]
Meter=Image
SolidColor=0,0,0,220
W=#workareawidth#
H=(762/2)
X=0
Y=(768/2+[move00])
UpdateDivider=1
DynamicVariables=1

[LogIn]
Meter=Image
ImageName=#@#Images\files\bg01.png
ImageTint=#color2#
W=800
H=[BangOutH]
X=(683-800/2)
Y=(384-[BangOutH]/2)
UpdateDivider=1
DynamicVariables=1

[Insignia0]
Meter=Image
ImageName=#@#Images\#Insignia#.png
ImageTint=#color1#,[Fade]
w=65
h=65
x=995
y=190
DynamicVariables=1
Hidden=1

[Online]
Meter=String
FontColor=#Color1#,[Fade]
MeterStyle=IntroStyle2
Text=SYSTEM ONLINE
DynamicVariables=1
Hidden=1

[DamageStats]
Meter=String
MeterStyle=IntroStyle2
MeasureName=Damage1
Text=#Damage1#
Hidden=1

[DamageStats1]
Meter=String
MeterStyle=IntroStyle2
MeasureName=Damage2a
Hidden=1
Group=DamageReport

[DamageStats2]
Meter=String
MeterStyle=IntroStyle2
MeasureName=Damage2b
Hidden=1
Group=DamageReport

[DamageStats3]
Meter=String
MeterStyle=IntroStyle2
Text=#Damage2c#
Hidden=1
Group=DamageReport

[DamageStats4]
Meter=String
MeterStyle=IntroStyle2
Text=#Damage2d#
Hidden=1
Group=DamageReport

[DamageStats5]
Meter=String
MeterStyle=IntroStyle2
Text=#Damage2e#
Hidden=1
Group=DamageReport

[Navigation]
Meter=String
MeterStyle=IntroStyle2
Text="Navigation Systems Initiated"
Hidden=1

[Location]
Meter=String
MeterStyle=IntroStyle2
Text=#Location1#
DynamicVariables=1
Hidden=1

[ComLinks]
Meter=String
MeterStyle=IntroStyle2
Text=#ComLink1#
Hidden=1
Group=startup

[BattleCity]
Measure=Calc
Formula=Random
LowBound=1
HighBound=9
Substitute="1":"Kaon","2":"Iacon","3":"Kalis","4":"Tyger Pax","5":"Praxus","6":"Gygax","7":"PolyHex","8":"Ankmor Park","9":"Altihex"
OnChangeAction=[!PauseMeasure BattleCity]
DynamicVariables=1

[BattleCalc]
Measure=Calc
Formula=Random
LowBound=1
HighBound=5
Substitute="1":"Autobots Captured [BattleCity]","2":"Decepticons Captured [BattleCity]","3":"Intense Battle at [BattleCity]","4":"Decepticons Assaulting Moon Base-1","5":"Decepticon Assault halted by Moon Base-1"
OnChangeAction=[!PauseMeasure BattleCalc]
DynamicVariables=1

[BattleStats]
Meter=String
Text=#Battle1#
MeterStyle=IntroStyle2
Hidden=1
DynamicVariables=1
Group=startup

[EnergonPercent]
Measure=Plugin
Plugin=PowerPlugin.dll
PowerState=PERCENT
UpdateDivider=20
IfCondition=(EnergonPercent > 75)
IfTrueAction=[!SetVariable EnergonLevel "Very High"]
IfCondition2=(EnergonPercent < 76)
IfTrueAction2=[!SetVariable EnergonLevel "Optimal"]
IfCondition3=(EnergonPercent < 51)
IfTrueAction3=[!SetVariable EnergonLevel "Fallen"]
IfCondition4=(EnergonPercent < 26)
IfTrueAction4=[!SetVariable EnergonLevel "Very Low"]
IfCondition5=(EnergonPercent < 13)
IfTrueAction5=[!SetVariable EnergonLevel "Critical"]
Group=startup

[EnergonStats]
Meter=String
Text=#Energon1#
MeterStyle=IntroStyle2
Hidden=1

[WeaponCalc]
Measure=Calc
Formula=Random
LowBound=1
HighBound=5
Substitute="1":"Locked 'n Loaded","2":"Projectiles Energized","3":"Cannons Charged Up","4":"Bladed Sharp","5":"Serrating Edges"
OnChangeAction=[!PauseMeasure WeaponCalc]
DynamicVariables=1

[WeaponStats]
Meter=String
Text=#Weapon1#
MeterStyle=IntroStyle2
DynamicVariables=1
Hidden=1

[HQLocate]
Meter=String
Text=#HQ1#
MeterStyle=IntroStyle2
Hidden=1

[CLF]
Meter=String
MeterStyle=IntroStyle2
Hidden=1
Text="HQ Comlink Frequency Accessed"

[GroundBridge]
Meter=String
Text=#Ground1#
MeterStyle=IntroStyle2
Hidden=1

[ROLLOUT]
Meter=String
Text="All Hail Megatron!"
MeterStyle=IntroStyle2
Hidden=1
