[RainMeter]
Update=100

[Metadata]
Name=Autobots Rainmeter Skin
Author=Rajnoor Brar
License=Creative Commons Attribution-NonCommercial Share-Alike 4.0 International

[variables]
@include=#@#\Config.inc
Color1=#Botcolor1#
Color2=#Botcolor2#
Color3=#Botcolor3#
Faction=Autobots
Insignia=botInsignia

[IntroHead]
FontColor=#Color1#,250
FontEffectColor=0,0,0,100
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=Center
FontFace=Autobus
FontSize=25
X=(1366/2)
Y=205
AntiAlias=1 

[IntroStyle1]
FontColor=0,0,0
FontEffectColor=#color1#,20
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=Left
FontFace=Autobus
FontSize=16
UpdateDivider=1
X=325
Y=R
AntiAlias=1

[IntroStyle1a]
FontColor=#Color2#,230
FontEffectColor=0,0,0,100
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=Left
FontFace=Autobus
FontSize=13
UpdateDivider=1
X=355
Y=R
AntiAlias=1

[IntroStyle2]
FontColor=#Color1#,250
FontEffectColor=0,0,0,200
StringEffect=BORDER
StringStyle=NORMAL
StringAlign=CenterCenter
FontFace=Autobus
FontSize=35
UpdateDivider=1
InlinePattern=#CRLF#(.*)
InlineSetting=Size | 27
w=800
h=450
X=(1366/2)
Y=(768/2)
AntiAlias=1

[TextStyle1]
FontColor=#Color1#,255
FontEffectColor=0,0,0,80
StringEffect=BORDER
StringStyle=NORMAL
FontFace=Cyberverse Condensed
AntiAlias=1

[TextStyle2]
FontColor=#Color2#,255
FontEffectColor=255,0,0,30
StringEffect=BORDER
StringStyle=NORMAL
FontFace=Cyberverse Condensed
AntiAlias=1

[TextStyle3]
FontColor=#Color1#,250
FontEffectColor=0,0,0,100
StringEffect=BORDER
StringStyle=NORMAL
FontFace=Autobus
AntiAlias=1

;===================================
[move00]
Measure=Calc
Formula=move00+(768/30)
DynamicVariables=1
Disabled=1

[BlurA]
Meter=Image
SolidColor=0,0,0,240
W=#workareawidth#
H=(768/2)
X=0
Y=(0-[move00])
DynamicVariables=1

[BlurB]
Meter=Image
SolidColor=0,0,0,240
W=#workareawidth#
H=(762/2)
X=0
Y=(768/2+[move00])
UpdateDivider=1

[ActionTimer]
Measure=Calc
Formula=ActionTimer+1
;-----
IfCondition=(ActionTimer=12)
IfTrueAction=[!SetOption Welcome Text "The War is Enraging as time passes"]
;-----
IfCondition2=(ActionTimer=25)
IfTrueAction2=[!SetOption Welcome Text "Earth Units of both Factions need reinforcements"]
;-----
IfCondition3=(ActionTimer= 40)
IfTrueAction3=[!SetOption Welcome Text "Select your Side and get into the BattleField"]
;-----
IfCondition=(ActionTimer= )
IfTrueAction=
;-----
IfCondition=(ActionTimer= )
IfTrueAction=


[Welcome]
Meter=String
MeterStyle=IntroStyle2
Text= Attention! New Protoform
